name: "Markdown Linter"
description: "Runs write-good or proselint on all .md files in the repository."
inputs:
  tool:
    description: "The tool to use for linting. Must be either write-good or proselint."
    required: true
    default: "write-good"
  ignore_paths:
    description: "Paths to ignore when linting."
    required: false
    default: ""
outputs:
  result: # id of output
    description: "The result of the linting."
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    INPUT_TOOL: ${{ inputs.tool }}
    INPUT_IGNORE_PATHS: ${{ inputs.ignore_paths }}
