name: 'Markdown Linter'
description: 'Runs write-good or proselint on all .md files in the repository.'
inputs:
  tool:
    description: 'The tool to use for linting. Must be either write-good or proselint.'
    required: true
    default: 'write-good'
outputs:
  result: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.tool }}
steps:
  - name: Upload lint log
    uses: actions/upload-artifact@v2
    with:
      name: lint-log
      path: lint.log
